version: "3.9"

services:
  postgres_db:
    image: postgres
    env_file:
      - ./docker/postgres/db.env
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  web:
    build: .
    command: gunicorn studentLabTask.wsgi:application
    volumes:
      - ./static:/games/static
    depends_on:
      - postgres_db
    ports:
      - "8000:8000"

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - web
    ports:
      - "80:80"

  celery:
    build: .
    command: -A studentLabTask worker -l INFO
    depends_on:
      - postgres_db
      - redis

  refresher:
    build: .
    command: -A studentLabTask beat -l INFO
    depends_on:
      - celery
      - postgres_db
      - redis