version: "3.9"

services:
  postgres_db:
    image: postgres
    env_file:
      - ./docker/postgres/db.env
    ports:
      - "5432:5432"

  broker:
    image: redis
    ports:
      - "6379:6379"

  web:
    build: .
    volumes:
      - ./:/games
    env_file:
      - studentLabTask/.env
    depends_on:
      - postgres_db
      - broker
    ports:
      - "8000:8000"