version: "3.9"

services:
  postgres_db:
    build: ./docker/postgres
    env_file:
      - ./docker/postgres/db.env
    ports:
      - "5432:5432"

  redis:
    build: ./docker/redis
    ports:
      - "6379:6379"

  web:
    build: .
    volumes:
      - ./:/games
    env_file:
      - studentLabTask/.env
    depends_on:
      - postgres_db
    ports:
      - "8000:8000"

  nginx:
    build: ./docker/nginx
    volumes:
      - ./static:/static
    ports:
      - "80:80"
    depends_on:
      - web

  game_refresh_receiver:
    build:
      context: .
      dockerfile: ./docker/celery_receiver/Dockerfile
    volumes:
      - ./:/games
    env_file:
      - studentLabTask/.env
    depends_on:
      - postgres_db
      - redis

  game_refresh_sender:
    build:
      context: .
      dockerfile: ./docker/celery_sender/Dockerfile
    volumes:
      - ./:/games
    env_file:
      - studentLabTask/.env
    depends_on:
      - game_refresh_receiver
      - postgres_db
      - redis