version: "3"

services:
  postgres_db:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER="${DATABASE_USER}"
      - POSTGRES_DB="${DATABASE_NAME}"
      - POSTGRES_PASSWORD="${DATABASE_PASSWORD}"
    ports:
      -"5432:5432"

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    valumes:
      - ./:/games
    depends_on:
      - postgres_db
    ports:
      -"8000:8000"