version: "3.9"

services:
  postgres_db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - db.env
    ports:
      - "5432:5432"

  web:
    build: .
    volumes:
      - ./:/games
    env_file:
      - studentLabTask/.env
    depends_on:
      - postgres_db
    ports:
      - "8000:8000"