# Generated by Django 3.1.7 on 2021-04-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210419_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=None, null=True, verbose_name='Birthday'),
        ),
    ]
