# Generated by Django 3.1.7 on 2021-05-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameMuster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='critics_rating',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='critics_rating_count',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='user_rating',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='user_rating_count',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
