# Generated by Django 3.1.7 on 2021-04-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("gameMuster", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="favoritegame",
            name="deleted",
            field=models.DateTimeField(default=None, null=True),
        )
    ]
